[package]
name = "terminal-ddos-visualizer"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
crossterm = "0.29.0"
geolocation = "0.2.1"
ratatui = "0.29.0"
reqwest = {version = "0.12.25", features = ["json"]}
serde = "1.0.228"
trpl = "0.3.0"
